### ISSUE TITLE
Why two tables to manage jobs 🤔?

### ISSUE THREAD

**Issue by olivierobert** [nhutle/laravel-crawler-app#6]
There are two tables for jobs:
- `jobs`
- `failed_jobs`

Why having two tables instead of having a single table to track the status for each job?

**Comment by nhutle** [comment]
Hi,

There are 2 reasons to separate them into 2 tables:

- Convenience: to look for an unsuccessful job that you want to retry or remove completely, you can find it easily on `failed_jobs` table. Laravel defines a mechanism working as below:
    + If a job is executed successfully, Laravel will remove this record from `jobs` table.
    + If a jon fail to execute and exceed max try (e.g. --tries=5), Laravel will insert it to `failed_jobs` table within extra field such as "exception", "failed_at", etc. to fully describe issue, then slightly remove it from `jobs` table.

- Performance: store all jobs in a single table would hurt performance. The query workers have to spent more time to query and pick up a new job to run. As time goes by, `jobs` table could store million of jobs that really reduce workers speed.

**Comment by nhutle** [comment]
By the way, I have fixed all other issues, created pull request and merged them to master ^^

**Comment by olivierobert** [comment]
The issue in having separate tables is that in case if error in the execution of the jobs, the new record in `failed_jobs` would never be created. At the minimum, there should be a field just as `attempted_at` or `last_executed_at` in the `jobs` table to know this job ran already. 

Also as a best practice, jobs should never be deleted from the `jobs` table for auditing purposes. How one would know if the job ran successfully at all if it's deleted. Maybe it was never inserted in to the `job` table in the first place. That's why usually there is a pruning mechanism with soft delete i.e. adding column with `deleted_at`. This allows to filter the table for non-deleted jobs.

**Comment by nhutle** [comment]
Totally agree. For auditing purpose, it's a must to store all jobs with its `status` (enum success/failed) plus extra fields such as `attempted_at`, `deleted_at`, `created_at`, `attempts`, `complete_at`, etc. to trace its status better. So better to merge them into 1 table only instead of having both.

**Comment by nhutle** [comment]
Hi Olivier, 

I've updated code to adopt auditing purpose. There is table called `tasks` to store all jobs by keywords, which includes following fields: 'keyword', 'status', 'created_at', 'attempts' (maximum = 3 attempts), 'updated_at' (last attempt at), 'exception' (to store any exception causes a failed job in order to reproduce bug), 'deleted_at'. Beside, there is a cron to soft delete `tasks` table every week. 

Please take a look at the pull request and let me know your thought about it.
